/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hla_rti1516e_openrti_ObjectClassHandleImpl */

#ifndef _Included_hla_rti1516e_openrti_ObjectClassHandleImpl
#define _Included_hla_rti1516e_openrti_ObjectClassHandleImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hla_rti1516e_openrti_ObjectClassHandleImpl
 * Method:    encode_rti
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_ObjectClassHandleImpl_encode_1rti
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     hla_rti1516e_openrti_ObjectClassHandleImpl
 * Method:    encodedLength_rti
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_hla_rti1516e_openrti_ObjectClassHandleImpl_encodedLength_1rti
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
