/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hla_rti1516e_openrti_RtiFactoryImpl */

#ifndef _Included_hla_rti1516e_openrti_RtiFactoryImpl
#define _Included_hla_rti1516e_openrti_RtiFactoryImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hla_rti1516e_openrti_RtiFactoryImpl
 * Method:    getRtiAmbassador_rti
 * Signature: ()Lhla/rti1516e/RTIambassador;
 */
JNIEXPORT jobject JNICALL Java_hla_rti1516e_openrti_RtiFactoryImpl_getRtiAmbassador_1rti
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
