/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hla_rti1516e_openrti_JniObject */

#ifndef _Included_hla_rti1516e_openrti_JniObject
#define _Included_hla_rti1516e_openrti_JniObject
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hla_rti1516e_openrti_JniObject
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_JniObject_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
