/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hla_rti1516e_openrti_RTIambassadorImpl */

#ifndef _Included_hla_rti1516e_openrti_RTIambassadorImpl
#define _Included_hla_rti1516e_openrti_RTIambassadorImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    decodeObjectInstanceHandle_rti
 * Signature: ([BI)Lhla/rti1516e/ObjectInstanceHandle;
 */
JNIEXPORT jobject JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_decodeObjectInstanceHandle_1rti
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    decodeObjectClassHandle_rti
 * Signature: ([BI)Lhla/rti1516e/ObjectClassHandle;
 */
JNIEXPORT jobject JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_decodeObjectClassHandle_1rti
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    decodeFederateHandle_rti
 * Signature: ([BI)Lhla/rti1516e/FederateHandle;
 */
JNIEXPORT jobject JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_decodeFederateHandle_1rti
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    decodeAttributeHandle_rti
 * Signature: ([BI)Lhla/rti1516e/AttributeHandle;
 */
JNIEXPORT jobject JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_decodeAttributeHandle_1rti
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    decodeParameterHandle_rti
 * Signature: ([BI)Lhla/rti1516e/ParameterHandle;
 */
JNIEXPORT jobject JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_decodeParameterHandle_1rti
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    connect_rti
 * Signature: (Lhla/rti1516e/FederateAmbassador;Lhla/rti1516e/CallbackModel;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_connect_1rti
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    disconnect_rti
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_disconnect_1rti
  (JNIEnv *, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    createFederationExecution_rti
 * Signature: (Ljava/lang/String;[Ljava/net/URL;Ljava/net/URL;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_createFederationExecution_1rti__Ljava_lang_String_2_3Ljava_net_URL_2Ljava_net_URL_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jobjectArray, jobject, jstring);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    createFederationExecution_rti
 * Signature: (Ljava/lang/String;[Ljava/net/URL;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_createFederationExecution_1rti__Ljava_lang_String_2_3Ljava_net_URL_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jobjectArray, jstring);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    createFederationExecution_rti
 * Signature: (Ljava/lang/String;[Ljava/net/URL;Ljava/net/URL;)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_createFederationExecution_1rti__Ljava_lang_String_2_3Ljava_net_URL_2Ljava_net_URL_2
  (JNIEnv *, jobject, jstring, jobjectArray, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    createFederationExecution_rti
 * Signature: (Ljava/lang/String;[Ljava/net/URL;)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_createFederationExecution_1rti__Ljava_lang_String_2_3Ljava_net_URL_2
  (JNIEnv *, jobject, jstring, jobjectArray);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    createFederationExecution_rti
 * Signature: (Ljava/lang/String;Ljava/net/URL;)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_createFederationExecution_1rti__Ljava_lang_String_2Ljava_net_URL_2
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    destroyFederationExecution_rti
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_destroyFederationExecution_1rti
  (JNIEnv *, jobject, jstring);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    listFederationExecutions_rti
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_listFederationExecutions_1rti
  (JNIEnv *, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    joinFederationExecution_rti
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[Ljava/net/URL;)Lhla/rti1516e/FederateHandle;
 */
JNIEXPORT jobject JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_joinFederationExecution_1rti__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2_3Ljava_net_URL_2
  (JNIEnv *, jobject, jstring, jstring, jstring, jobjectArray);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    joinFederationExecution_rti
 * Signature: (Ljava/lang/String;Ljava/lang/String;[Ljava/net/URL;)Lhla/rti1516e/FederateHandle;
 */
JNIEXPORT jobject JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_joinFederationExecution_1rti__Ljava_lang_String_2Ljava_lang_String_2_3Ljava_net_URL_2
  (JNIEnv *, jobject, jstring, jstring, jobjectArray);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    joinFederationExecution_rti
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Lhla/rti1516e/FederateHandle;
 */
JNIEXPORT jobject JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_joinFederationExecution_1rti__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    joinFederationExecution_rti
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Lhla/rti1516e/FederateHandle;
 */
JNIEXPORT jobject JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_joinFederationExecution_1rti__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    resignFederationExecution_rti
 * Signature: (Lhla/rti1516e/ResignAction;)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_resignFederationExecution_1rti
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    registerFederationSynchronizationPoint_rti
 * Signature: (Ljava/lang/String;[B)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_registerFederationSynchronizationPoint_1rti__Ljava_lang_String_2_3B
  (JNIEnv *, jobject, jstring, jbyteArray);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    registerFederationSynchronizationPoint_rti
 * Signature: (Ljava/lang/String;[BLhla/rti1516e/FederateHandleSet;)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_registerFederationSynchronizationPoint_1rti__Ljava_lang_String_2_3BLhla_rti1516e_FederateHandleSet_2
  (JNIEnv *, jobject, jstring, jbyteArray, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    synchronizationPointAchieved_rti
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_synchronizationPointAchieved_1rti__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    synchronizationPointAchieved_rti
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_synchronizationPointAchieved_1rti__Ljava_lang_String_2Z
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    requestFederationSave_rti
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_requestFederationSave_1rti__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    requestFederationSave_rti
 * Signature: (Ljava/lang/String;Lhla/rti1516e/LogicalTime;)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_requestFederationSave_1rti__Ljava_lang_String_2Lhla_rti1516e_LogicalTime_2
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    federateSaveBegun_rti
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_federateSaveBegun_1rti
  (JNIEnv *, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    federateSaveComplete_rti
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_federateSaveComplete_1rti
  (JNIEnv *, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    federateSaveNotComplete_rti
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_federateSaveNotComplete_1rti
  (JNIEnv *, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    abortFederationSave_rti
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_abortFederationSave_1rti
  (JNIEnv *, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    queryFederationSaveStatus_rti
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_queryFederationSaveStatus_1rti
  (JNIEnv *, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    requestFederationRestore_rti
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_requestFederationRestore_1rti
  (JNIEnv *, jobject, jstring);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    federateRestoreComplete_rti
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_federateRestoreComplete_1rti
  (JNIEnv *, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    federateRestoreNotComplete_rti
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_federateRestoreNotComplete_1rti
  (JNIEnv *, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    abortFederationRestore_rti
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_abortFederationRestore_1rti
  (JNIEnv *, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    queryFederationRestoreStatus_rti
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_queryFederationRestoreStatus_1rti
  (JNIEnv *, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    publishObjectClassAttributes_rti
 * Signature: (Lhla/rti1516e/ObjectClassHandle;[Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_publishObjectClassAttributes_1rti
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    unpublishObjectClass_rti
 * Signature: (Lhla/rti1516e/ObjectClassHandle;)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_unpublishObjectClass_1rti
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    unpublishObjectClassAttributes_rti
 * Signature: (Lhla/rti1516e/ObjectClassHandle;Lhla/rti1516e/AttributeHandleSet;)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_unpublishObjectClassAttributes_1rti
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    publishInteractionClass_rti
 * Signature: (Lhla/rti1516e/InteractionClassHandle;)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_publishInteractionClass_1rti
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    unpublishInteractionClass_rti
 * Signature: (Lhla/rti1516e/InteractionClassHandle;)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_unpublishInteractionClass_1rti
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    subscribeObjectClassAttributes_rti
 * Signature: (Lhla/rti1516e/ObjectClassHandle;[Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_subscribeObjectClassAttributes_1rti__Lhla_rti1516e_ObjectClassHandle_2_3Ljava_lang_Object_2
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    subscribeObjectClassAttributes_rti
 * Signature: (Lhla/rti1516e/ObjectClassHandle;Lhla/rti1516e/AttributeHandleSet;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_subscribeObjectClassAttributes_1rti__Lhla_rti1516e_ObjectClassHandle_2Lhla_rti1516e_AttributeHandleSet_2Ljava_lang_String_2
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    subscribeObjectClassAttributesPassively_rti
 * Signature: (Lhla/rti1516e/ObjectClassHandle;Lhla/rti1516e/AttributeHandleSet;)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_subscribeObjectClassAttributesPassively_1rti__Lhla_rti1516e_ObjectClassHandle_2Lhla_rti1516e_AttributeHandleSet_2
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    subscribeObjectClassAttributesPassively_rti
 * Signature: (Lhla/rti1516e/ObjectClassHandle;Lhla/rti1516e/AttributeHandleSet;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_subscribeObjectClassAttributesPassively_1rti__Lhla_rti1516e_ObjectClassHandle_2Lhla_rti1516e_AttributeHandleSet_2Ljava_lang_String_2
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    unsubscribeObjectClass_rti
 * Signature: (Lhla/rti1516e/ObjectClassHandle;)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_unsubscribeObjectClass_1rti
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    unsubscribeObjectClassAttributes_rti
 * Signature: (Lhla/rti1516e/ObjectClassHandle;Lhla/rti1516e/AttributeHandleSet;)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_unsubscribeObjectClassAttributes_1rti
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    subscribeInteractionClass_rti
 * Signature: (Lhla/rti1516e/InteractionClassHandle;)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_subscribeInteractionClass_1rti
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    subscribeInteractionClassPassively_rti
 * Signature: (Lhla/rti1516e/InteractionClassHandle;)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_subscribeInteractionClassPassively_1rti
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    unsubscribeInteractionClass_rti
 * Signature: (Lhla/rti1516e/InteractionClassHandle;)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_unsubscribeInteractionClass_1rti
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    reserveObjectInstanceName_rti
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_reserveObjectInstanceName_1rti
  (JNIEnv *, jobject, jstring);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    releaseObjectInstanceName_rti
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_releaseObjectInstanceName_1rti
  (JNIEnv *, jobject, jstring);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    reserveMultipleObjectInstanceName_rti
 * Signature: (Ljava/util/Set;)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_reserveMultipleObjectInstanceName_1rti
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    releaseMultipleObjectInstanceName_rti
 * Signature: (Ljava/util/Set;)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_releaseMultipleObjectInstanceName_1rti
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    registerObjectInstance_rti
 * Signature: (Lhla/rti1516e/ObjectClassHandle;)Lhla/rti1516e/ObjectInstanceHandle;
 */
JNIEXPORT jobject JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_registerObjectInstance_1rti__Lhla_rti1516e_ObjectClassHandle_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    registerObjectInstance_rti
 * Signature: (Lhla/rti1516e/ObjectClassHandle;Ljava/lang/String;)Lhla/rti1516e/ObjectInstanceHandle;
 */
JNIEXPORT jobject JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_registerObjectInstance_1rti__Lhla_rti1516e_ObjectClassHandle_2Ljava_lang_String_2
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    updateAttributeValues_rti
 * Signature: (Lhla/rti1516e/ObjectInstanceHandle;[Ljava/lang/Object;[B)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_updateAttributeValues_1rti
  (JNIEnv *, jobject, jobject, jobjectArray, jbyteArray);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    updateAttributeValuesFloat64_rti
 * Signature: (Lhla/rti1516e/ObjectInstanceHandle;[Ljava/lang/Object;[BD)Lhla/rti1516e/MessageRetractionReturn;
 */
JNIEXPORT jobject JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_updateAttributeValuesFloat64_1rti
  (JNIEnv *, jobject, jobject, jobjectArray, jbyteArray, jdouble);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    updateAttributeValuesInteger64_rti
 * Signature: (Lhla/rti1516e/ObjectInstanceHandle;[Ljava/lang/Object;[BJ)Lhla/rti1516e/MessageRetractionReturn;
 */
JNIEXPORT jobject JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_updateAttributeValuesInteger64_1rti
  (JNIEnv *, jobject, jobject, jobjectArray, jbyteArray, jlong);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    sendInteraction_rti
 * Signature: (Lhla/rti1516e/InteractionClassHandle;[Ljava/lang/Object;[B)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_sendInteraction_1rti
  (JNIEnv *, jobject, jobject, jobjectArray, jbyteArray);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    sendInteractionInteger64_rti
 * Signature: (Lhla/rti1516e/InteractionClassHandle;[Ljava/lang/Object;[BJ)Lhla/rti1516e/MessageRetractionReturn;
 */
JNIEXPORT jobject JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_sendInteractionInteger64_1rti
  (JNIEnv *, jobject, jobject, jobjectArray, jbyteArray, jlong);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    sendInteractionFloat64_rti
 * Signature: (Lhla/rti1516e/InteractionClassHandle;[Ljava/lang/Object;[BD)Lhla/rti1516e/MessageRetractionReturn;
 */
JNIEXPORT jobject JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_sendInteractionFloat64_1rti
  (JNIEnv *, jobject, jobject, jobjectArray, jbyteArray, jdouble);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    deleteObjectInstance_rti
 * Signature: (Lhla/rti1516e/ObjectInstanceHandle;[B)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_deleteObjectInstance_1rti__Lhla_rti1516e_ObjectInstanceHandle_2_3B
  (JNIEnv *, jobject, jobject, jbyteArray);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    deleteObjectInstance_rti
 * Signature: (Lhla/rti1516e/ObjectInstanceHandle;[BLhla/rti1516e/LogicalTime;)Lhla/rti1516e/MessageRetractionReturn;
 */
JNIEXPORT jobject JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_deleteObjectInstance_1rti__Lhla_rti1516e_ObjectInstanceHandle_2_3BLhla_rti1516e_LogicalTime_2
  (JNIEnv *, jobject, jobject, jbyteArray, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    localDeleteObjectInstance_rti
 * Signature: (Lhla/rti1516e/ObjectInstanceHandle;)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_localDeleteObjectInstance_1rti
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    requestAttributeValueUpdate_rti
 * Signature: (Lhla/rti1516e/ObjectInstanceHandle;[Ljava/lang/Object;[B)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_requestAttributeValueUpdate_1rti__Lhla_rti1516e_ObjectInstanceHandle_2_3Ljava_lang_Object_2_3B
  (JNIEnv *, jobject, jobject, jobjectArray, jbyteArray);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    requestAttributeValueUpdate_rti
 * Signature: (Lhla/rti1516e/ObjectClassHandle;[Ljava/lang/Object;[B)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_requestAttributeValueUpdate_1rti__Lhla_rti1516e_ObjectClassHandle_2_3Ljava_lang_Object_2_3B
  (JNIEnv *, jobject, jobject, jobjectArray, jbyteArray);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    requestAttributeTransportationTypeChange_rti
 * Signature: (Lhla/rti1516e/ObjectInstanceHandle;Lhla/rti1516e/AttributeHandleSet;Lhla/rti1516e/TransportationTypeHandle;)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_requestAttributeTransportationTypeChange_1rti
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    queryAttributeTransportationType_rti
 * Signature: (Lhla/rti1516e/ObjectInstanceHandle;Lhla/rti1516e/AttributeHandle;)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_queryAttributeTransportationType_1rti
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    requestInteractionTransportationTypeChange_rti
 * Signature: (Lhla/rti1516e/InteractionClassHandle;Lhla/rti1516e/TransportationTypeHandle;)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_requestInteractionTransportationTypeChange_1rti
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    queryInteractionTransportationType_rti
 * Signature: (Lhla/rti1516e/FederateHandle;Lhla/rti1516e/InteractionClassHandle;)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_queryInteractionTransportationType_1rti
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    unconditionalAttributeOwnershipDivestiture_rti
 * Signature: (Lhla/rti1516e/ObjectInstanceHandle;Lhla/rti1516e/AttributeHandleSet;)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_unconditionalAttributeOwnershipDivestiture_1rti
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    negotiatedAttributeOwnershipDivestiture_rti
 * Signature: (Lhla/rti1516e/ObjectInstanceHandle;Lhla/rti1516e/AttributeHandleSet;[B)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_negotiatedAttributeOwnershipDivestiture_1rti
  (JNIEnv *, jobject, jobject, jobject, jbyteArray);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    confirmDivestiture_rti
 * Signature: (Lhla/rti1516e/ObjectInstanceHandle;Lhla/rti1516e/AttributeHandleSet;[B)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_confirmDivestiture_1rti
  (JNIEnv *, jobject, jobject, jobject, jbyteArray);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    attributeOwnershipAcquisition_rti
 * Signature: (Lhla/rti1516e/ObjectInstanceHandle;Lhla/rti1516e/AttributeHandleSet;[B)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_attributeOwnershipAcquisition_1rti
  (JNIEnv *, jobject, jobject, jobject, jbyteArray);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    attributeOwnershipAcquisitionIfAvailable_rti
 * Signature: (Lhla/rti1516e/ObjectInstanceHandle;Lhla/rti1516e/AttributeHandleSet;)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_attributeOwnershipAcquisitionIfAvailable_1rti
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    attributeOwnershipReleaseDenied_rti
 * Signature: (Lhla/rti1516e/ObjectInstanceHandle;Lhla/rti1516e/AttributeHandleSet;)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_attributeOwnershipReleaseDenied_1rti
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    attributeOwnershipDivestitureIfWanted_rti
 * Signature: (Lhla/rti1516e/ObjectInstanceHandle;Lhla/rti1516e/AttributeHandleSet;)Lhla/rti1516e/AttributeHandleSet;
 */
JNIEXPORT jobject JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_attributeOwnershipDivestitureIfWanted_1rti
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    cancelNegotiatedAttributeOwnershipDivestiture_rti
 * Signature: (Lhla/rti1516e/ObjectInstanceHandle;Lhla/rti1516e/AttributeHandleSet;)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_cancelNegotiatedAttributeOwnershipDivestiture_1rti
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    cancelAttributeOwnershipAcquisition_rti
 * Signature: (Lhla/rti1516e/ObjectInstanceHandle;Lhla/rti1516e/AttributeHandleSet;)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_cancelAttributeOwnershipAcquisition_1rti
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    queryAttributeOwnership_rti
 * Signature: (Lhla/rti1516e/ObjectInstanceHandle;Lhla/rti1516e/AttributeHandle;)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_queryAttributeOwnership_1rti
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    isAttributeOwnedByFederate_rti
 * Signature: (Lhla/rti1516e/ObjectInstanceHandle;Lhla/rti1516e/AttributeHandle;)Z
 */
JNIEXPORT jboolean JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_isAttributeOwnedByFederate_1rti
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    enableTimeRegulationInteger64_rti
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_enableTimeRegulationInteger64_1rti
  (JNIEnv *, jobject, jlong);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    enableTimeRegulationFloat64_rti
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_enableTimeRegulationFloat64_1rti
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    disableTimeRegulation_rti
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_disableTimeRegulation_1rti
  (JNIEnv *, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    enableTimeConstrained_rti
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_enableTimeConstrained_1rti
  (JNIEnv *, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    disableTimeConstrained_rti
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_disableTimeConstrained_1rti
  (JNIEnv *, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    timeAdvanceRequestInteger64_rti
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_timeAdvanceRequestInteger64_1rti
  (JNIEnv *, jobject, jlong);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    timeAdvanceRequestFloat64_rti
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_timeAdvanceRequestFloat64_1rti
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    timeAdvanceRequestAvailable_rti
 * Signature: (Lhla/rti1516e/LogicalTime;)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_timeAdvanceRequestAvailable_1rti
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    nextMessageRequest_rti
 * Signature: (Lhla/rti1516e/LogicalTime;)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_nextMessageRequest_1rti
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    nextMessageRequestAvailable_rti
 * Signature: (Lhla/rti1516e/LogicalTime;)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_nextMessageRequestAvailable_1rti
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    flushQueueRequest_rti
 * Signature: (Lhla/rti1516e/LogicalTime;)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_flushQueueRequest_1rti
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    enableAsynchronousDelivery_rti
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_enableAsynchronousDelivery_1rti
  (JNIEnv *, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    disableAsynchronousDelivery_rti
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_disableAsynchronousDelivery_1rti
  (JNIEnv *, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    queryGALT_rti
 * Signature: ()Lhla/rti1516e/TimeQueryReturn;
 */
JNIEXPORT jobject JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_queryGALT_1rti
  (JNIEnv *, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    queryLogicalTime_rti
 * Signature: ()Lhla/rti1516e/LogicalTime;
 */
JNIEXPORT jobject JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_queryLogicalTime_1rti
  (JNIEnv *, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    queryLITS_rti
 * Signature: ()Lhla/rti1516e/TimeQueryReturn;
 */
JNIEXPORT jobject JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_queryLITS_1rti
  (JNIEnv *, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    modifyLookahead_rti
 * Signature: (Lhla/rti1516e/LogicalTimeInterval;)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_modifyLookahead_1rti
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    queryLookahead_rti
 * Signature: ()Lhla/rti1516e/LogicalTimeInterval;
 */
JNIEXPORT jobject JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_queryLookahead_1rti
  (JNIEnv *, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    retract_rti
 * Signature: (Lhla/rti1516e/MessageRetractionHandle;)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_retract_1rti
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    changeAttributeOrderType_rti
 * Signature: (Lhla/rti1516e/ObjectInstanceHandle;Lhla/rti1516e/AttributeHandleSet;Lhla/rti1516e/OrderType;)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_changeAttributeOrderType_1rti
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    changeInteractionOrderType_rti
 * Signature: (Lhla/rti1516e/InteractionClassHandle;Lhla/rti1516e/OrderType;)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_changeInteractionOrderType_1rti
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    createRegion_rti
 * Signature: (Lhla/rti1516e/DimensionHandleSet;)Lhla/rti1516e/RegionHandle;
 */
JNIEXPORT jobject JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_createRegion_1rti
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    commitRegionModifications_rti
 * Signature: (Lhla/rti1516e/RegionHandleSet;)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_commitRegionModifications_1rti
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    deleteRegion_rti
 * Signature: (Lhla/rti1516e/RegionHandle;)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_deleteRegion_1rti
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    registerObjectInstanceWithRegions_rti
 * Signature: (Lhla/rti1516e/ObjectClassHandle;Lhla/rti1516e/AttributeSetRegionSetPairList;)Lhla/rti1516e/ObjectInstanceHandle;
 */
JNIEXPORT jobject JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_registerObjectInstanceWithRegions_1rti__Lhla_rti1516e_ObjectClassHandle_2Lhla_rti1516e_AttributeSetRegionSetPairList_2
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    registerObjectInstanceWithRegions_rti
 * Signature: (Lhla/rti1516e/ObjectClassHandle;Lhla/rti1516e/AttributeSetRegionSetPairList;Ljava/lang/String;)Lhla/rti1516e/ObjectInstanceHandle;
 */
JNIEXPORT jobject JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_registerObjectInstanceWithRegions_1rti__Lhla_rti1516e_ObjectClassHandle_2Lhla_rti1516e_AttributeSetRegionSetPairList_2Ljava_lang_String_2
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    associateRegionsForUpdates_rti
 * Signature: (Lhla/rti1516e/ObjectInstanceHandle;Lhla/rti1516e/AttributeSetRegionSetPairList;)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_associateRegionsForUpdates_1rti
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    unassociateRegionsForUpdates_rti
 * Signature: (Lhla/rti1516e/ObjectInstanceHandle;Lhla/rti1516e/AttributeSetRegionSetPairList;)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_unassociateRegionsForUpdates_1rti
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    subscribeObjectClassAttributesWithRegions_rti
 * Signature: (Lhla/rti1516e/ObjectClassHandle;Lhla/rti1516e/AttributeSetRegionSetPairList;)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_subscribeObjectClassAttributesWithRegions_1rti__Lhla_rti1516e_ObjectClassHandle_2Lhla_rti1516e_AttributeSetRegionSetPairList_2
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    subscribeObjectClassAttributesWithRegions_rti
 * Signature: (Lhla/rti1516e/ObjectClassHandle;Lhla/rti1516e/AttributeSetRegionSetPairList;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_subscribeObjectClassAttributesWithRegions_1rti__Lhla_rti1516e_ObjectClassHandle_2Lhla_rti1516e_AttributeSetRegionSetPairList_2Ljava_lang_String_2
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    subscribeObjectClassAttributesPassivelyWithRegions_rti
 * Signature: (Lhla/rti1516e/ObjectClassHandle;Lhla/rti1516e/AttributeSetRegionSetPairList;)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_subscribeObjectClassAttributesPassivelyWithRegions_1rti__Lhla_rti1516e_ObjectClassHandle_2Lhla_rti1516e_AttributeSetRegionSetPairList_2
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    subscribeObjectClassAttributesPassivelyWithRegions_rti
 * Signature: (Lhla/rti1516e/ObjectClassHandle;Lhla/rti1516e/AttributeSetRegionSetPairList;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_subscribeObjectClassAttributesPassivelyWithRegions_1rti__Lhla_rti1516e_ObjectClassHandle_2Lhla_rti1516e_AttributeSetRegionSetPairList_2Ljava_lang_String_2
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    unsubscribeObjectClassAttributesWithRegions_rti
 * Signature: (Lhla/rti1516e/ObjectClassHandle;Lhla/rti1516e/AttributeSetRegionSetPairList;)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_unsubscribeObjectClassAttributesWithRegions_1rti
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    subscribeInteractionClassWithRegions_rti
 * Signature: (Lhla/rti1516e/InteractionClassHandle;Lhla/rti1516e/RegionHandleSet;)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_subscribeInteractionClassWithRegions_1rti
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    subscribeInteractionClassPassivelyWithRegions_rti
 * Signature: (Lhla/rti1516e/InteractionClassHandle;Lhla/rti1516e/RegionHandleSet;)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_subscribeInteractionClassPassivelyWithRegions_1rti
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    unsubscribeInteractionClassWithRegions_rti
 * Signature: (Lhla/rti1516e/InteractionClassHandle;Lhla/rti1516e/RegionHandleSet;)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_unsubscribeInteractionClassWithRegions_1rti
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    sendInteractionWithRegions_rti
 * Signature: (Lhla/rti1516e/InteractionClassHandle;Lhla/rti1516e/ParameterHandleValueMap;Lhla/rti1516e/RegionHandleSet;[B)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_sendInteractionWithRegions_1rti__Lhla_rti1516e_InteractionClassHandle_2Lhla_rti1516e_ParameterHandleValueMap_2Lhla_rti1516e_RegionHandleSet_2_3B
  (JNIEnv *, jobject, jobject, jobject, jobject, jbyteArray);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    sendInteractionWithRegions_rti
 * Signature: (Lhla/rti1516e/InteractionClassHandle;Lhla/rti1516e/ParameterHandleValueMap;Lhla/rti1516e/RegionHandleSet;[BLhla/rti1516e/LogicalTime;)Lhla/rti1516e/MessageRetractionReturn;
 */
JNIEXPORT jobject JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_sendInteractionWithRegions_1rti__Lhla_rti1516e_InteractionClassHandle_2Lhla_rti1516e_ParameterHandleValueMap_2Lhla_rti1516e_RegionHandleSet_2_3BLhla_rti1516e_LogicalTime_2
  (JNIEnv *, jobject, jobject, jobject, jobject, jbyteArray, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    requestAttributeValueUpdateWithRegions_rti
 * Signature: (Lhla/rti1516e/ObjectClassHandle;Lhla/rti1516e/AttributeSetRegionSetPairList;[B)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_requestAttributeValueUpdateWithRegions_1rti
  (JNIEnv *, jobject, jobject, jobject, jbyteArray);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    getAutomaticResignDirective_rti
 * Signature: ()Lhla/rti1516e/ResignAction;
 */
JNIEXPORT jobject JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_getAutomaticResignDirective_1rti
  (JNIEnv *, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    setAutomaticResignDirective_rti
 * Signature: (Lhla/rti1516e/ResignAction;)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_setAutomaticResignDirective_1rti
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    getFederateHandle_rti
 * Signature: (Ljava/lang/String;)Lhla/rti1516e/FederateHandle;
 */
JNIEXPORT jobject JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_getFederateHandle_1rti
  (JNIEnv *, jobject, jstring);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    getFederateName_rti
 * Signature: (Lhla/rti1516e/FederateHandle;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_getFederateName_1rti
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    getObjectClassHandle_rti
 * Signature: (Ljava/lang/String;)Lhla/rti1516e/ObjectClassHandle;
 */
JNIEXPORT jobject JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_getObjectClassHandle_1rti
  (JNIEnv *, jobject, jstring);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    getObjectClassName_rti
 * Signature: (Lhla/rti1516e/ObjectClassHandle;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_getObjectClassName_1rti
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    getKnownObjectClassHandle_rti
 * Signature: (Lhla/rti1516e/ObjectInstanceHandle;)Lhla/rti1516e/ObjectClassHandle;
 */
JNIEXPORT jobject JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_getKnownObjectClassHandle_1rti
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    getObjectInstanceHandle_rti
 * Signature: (Ljava/lang/String;)Lhla/rti1516e/ObjectInstanceHandle;
 */
JNIEXPORT jobject JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_getObjectInstanceHandle_1rti
  (JNIEnv *, jobject, jstring);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    getObjectInstanceName_rti
 * Signature: (Lhla/rti1516e/ObjectInstanceHandle;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_getObjectInstanceName_1rti
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    getAttributeHandle_rti
 * Signature: (Lhla/rti1516e/ObjectClassHandle;Ljava/lang/String;)Lhla/rti1516e/AttributeHandle;
 */
JNIEXPORT jobject JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_getAttributeHandle_1rti
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    getAttributeName_rti
 * Signature: (Lhla/rti1516e/ObjectClassHandle;Lhla/rti1516e/AttributeHandle;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_getAttributeName_1rti
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    getUpdateRateValue_rti
 * Signature: (Ljava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_getUpdateRateValue_1rti
  (JNIEnv *, jobject, jstring);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    getUpdateRateValueForAttribute_rti
 * Signature: (Lhla/rti1516e/ObjectInstanceHandle;Lhla/rti1516e/AttributeHandle;)D
 */
JNIEXPORT jdouble JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_getUpdateRateValueForAttribute_1rti
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    getInteractionClassHandle_rti
 * Signature: (Ljava/lang/String;)Lhla/rti1516e/InteractionClassHandle;
 */
JNIEXPORT jobject JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_getInteractionClassHandle_1rti
  (JNIEnv *, jobject, jstring);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    getInteractionClassName_rti
 * Signature: (Lhla/rti1516e/InteractionClassHandle;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_getInteractionClassName_1rti
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    getParameterHandle_rti
 * Signature: (Lhla/rti1516e/InteractionClassHandle;Ljava/lang/String;)Lhla/rti1516e/ParameterHandle;
 */
JNIEXPORT jobject JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_getParameterHandle_1rti
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    getParameterName_rti
 * Signature: (Lhla/rti1516e/InteractionClassHandle;Lhla/rti1516e/ParameterHandle;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_getParameterName_1rti
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    getOrderType_rti
 * Signature: (Ljava/lang/String;)Lhla/rti1516e/OrderType;
 */
JNIEXPORT jobject JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_getOrderType_1rti
  (JNIEnv *, jobject, jstring);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    getOrderName_rti
 * Signature: (Lhla/rti1516e/OrderType;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_getOrderName_1rti
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    getTransportationTypeHandle_rti
 * Signature: (Ljava/lang/String;)Lhla/rti1516e/TransportationTypeHandle;
 */
JNIEXPORT jobject JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_getTransportationTypeHandle_1rti
  (JNIEnv *, jobject, jstring);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    getTransportationTypeName_rti
 * Signature: (Lhla/rti1516e/TransportationTypeHandle;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_getTransportationTypeName_1rti
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    getAvailableDimensionsForClassAttribute_rti
 * Signature: (Lhla/rti1516e/ObjectClassHandle;Lhla/rti1516e/AttributeHandle;)Lhla/rti1516e/DimensionHandleSet;
 */
JNIEXPORT jobject JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_getAvailableDimensionsForClassAttribute_1rti
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    getAvailableDimensionsForInteractionClass_rti
 * Signature: (Lhla/rti1516e/InteractionClassHandle;)Lhla/rti1516e/DimensionHandleSet;
 */
JNIEXPORT jobject JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_getAvailableDimensionsForInteractionClass_1rti
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    getDimensionHandle_rti
 * Signature: (Ljava/lang/String;)Lhla/rti1516e/DimensionHandle;
 */
JNIEXPORT jobject JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_getDimensionHandle_1rti
  (JNIEnv *, jobject, jstring);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    getDimensionName_rti
 * Signature: (Lhla/rti1516e/DimensionHandle;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_getDimensionName_1rti
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    getDimensionUpperBound_rti
 * Signature: (Lhla/rti1516e/DimensionHandle;)J
 */
JNIEXPORT jlong JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_getDimensionUpperBound_1rti
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    getDimensionHandleSet_rti
 * Signature: (Lhla/rti1516e/RegionHandle;)Lhla/rti1516e/DimensionHandleSet;
 */
JNIEXPORT jobject JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_getDimensionHandleSet_1rti
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    getRangeBounds_rti
 * Signature: (Lhla/rti1516e/RegionHandle;Lhla/rti1516e/DimensionHandle;)Lhla/rti1516e/RangeBounds;
 */
JNIEXPORT jobject JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_getRangeBounds_1rti
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    setRangeBounds_rti
 * Signature: (Lhla/rti1516e/RegionHandle;Lhla/rti1516e/DimensionHandle;Lhla/rti1516e/RangeBounds;)V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_setRangeBounds_1rti
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    normalizeFederateHandle_rti
 * Signature: (Lhla/rti1516e/FederateHandle;)J
 */
JNIEXPORT jlong JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_normalizeFederateHandle_1rti
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    normalizeServiceGroup_rti
 * Signature: (Lhla/rti1516e/ServiceGroup;)J
 */
JNIEXPORT jlong JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_normalizeServiceGroup_1rti
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    enableObjectClassRelevanceAdvisorySwitch_rti
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_enableObjectClassRelevanceAdvisorySwitch_1rti
  (JNIEnv *, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    disableObjectClassRelevanceAdvisorySwitch_rti
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_disableObjectClassRelevanceAdvisorySwitch_1rti
  (JNIEnv *, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    enableAttributeRelevanceAdvisorySwitch_rti
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_enableAttributeRelevanceAdvisorySwitch_1rti
  (JNIEnv *, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    disableAttributeRelevanceAdvisorySwitch_rti
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_disableAttributeRelevanceAdvisorySwitch_1rti
  (JNIEnv *, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    enableAttributeScopeAdvisorySwitch_rti
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_enableAttributeScopeAdvisorySwitch_1rti
  (JNIEnv *, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    disableAttributeScopeAdvisorySwitch_rti
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_disableAttributeScopeAdvisorySwitch_1rti
  (JNIEnv *, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    enableInteractionRelevanceAdvisorySwitch_rti
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_enableInteractionRelevanceAdvisorySwitch_1rti
  (JNIEnv *, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    disableInteractionRelevanceAdvisorySwitch_rti
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_disableInteractionRelevanceAdvisorySwitch_1rti
  (JNIEnv *, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    evokeCallback_rti
 * Signature: (D)Z
 */
JNIEXPORT jboolean JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_evokeCallback_1rti
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    evokeMultipleCallbacks_rti
 * Signature: (DD)Z
 */
JNIEXPORT jboolean JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_evokeMultipleCallbacks_1rti
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    enableCallbacks_rti
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_enableCallbacks_1rti
  (JNIEnv *, jobject);

/*
 * Class:     hla_rti1516e_openrti_RTIambassadorImpl
 * Method:    disableCallbacks_rti
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hla_rti1516e_openrti_RTIambassadorImpl_disableCallbacks_1rti
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
